# Changing this file necessitates a server restart
name: "NeuroLibre"
abbreviation: "NeuroLibre"
doi_prefix: "10.55458"
issn: ""
tagline: "TEST a preprint server for <strong>reproducible</strong> data analyses."
logo_url: "https://conp-pcno.github.io/images/neurolibre-icon-red.png"
url: "https://staging.neurolibre.org"
editor_email: "editors@evidencepub.io"
noreply_email: "noreply@evidencepub.io"
twitter: "@NeuroLibre"
mastodon_url: ""
google_analytics: ""
github: "neurolibre/neurolibre-neo"
reviews: "neurolibre/neurolibre-reviews-testing"
papers_repo: "neurolibre/preprints-testing"
papers_html_url: "http://neurolibre.github.io/preprints-testing"
reviewers_signup_url: ""
product: "preprint" # the *thing* being submitted for review
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the NeuroLibre submission criteria.
paper_types: []
bot_username: roboneuro
