# Changing this file necessitates a server restart
name: "NeuroLibre"
abbreviation: "NeuroLibre"
issn: ""
tagline: "a <strong>next-gen</strong> preprint publisher for <s>neuro</s> all sciences."
logo_url: "https://conp-pcno.github.io/images/neurolibre-icon-red.png"
url: "http://0.0.0.0:5000"
editor_email: "editors@neurolibre.org"
noreply_email: "noreply@neurolibre.org"
twitter: "@NeuroLibre"
mastodon_url: ""
google_analytics: ""
github: "neurolibre/neurolibre-neo"
reviews: "neurolibre/neurolibre-reviews"
papers_repo: "neurolibre/neurolibre-papers"
papers_html_url: "https://neurolibre.github.io/preprints"
reviewers_signup_url: ""
product: "notebooks" # the *thing* being submitted for review
reviewers: "https://bit.ly/neurolibre_reviewers"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the NeuroLibre submission criteria.
paper_types: []
bot_username: roboneuro
